spring.application.name=student-api
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/SpringStu}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:12345}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true